# Generated by Django 4.1 on 2023-10-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('recording', models.BinaryField()),
                ('tablet', models.IntegerField()),
                ('for_role', models.IntegerField()),
                ('is_question', models.BooleanField()),
                ('time', models.DateTimeField()),
                ('state', models.IntegerField(choices=[(0, 'Waiting'), (1, 'Processing'), (2, 'Finished')], default=0)),
                ('response', models.TextField()),
                ('response_time', models.DateTimeField()),
            ],
        ),
    ]
