# Generated by Django 4.1 on 2023-10-29 14:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='for_role',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(3)]),
        ),
    ]
