# Generated by Django 4.1 on 2023-10-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_alter_request_for_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='response',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='response_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
