# Generated by Django 4.1 on 2023-10-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_alter_request_response_alter_request_response_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='response_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
