# Generated by Django 4.1.3 on 2023-10-29 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0003_alter_staff_nfc"),
        ("request", "0004_alter_request_response_alter_request_response_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="for_role",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="staff.role"
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="recording",
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name="request",
            name="time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
