# Generated by Django 4.1.3 on 2023-10-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("request", "0005_alter_request_for_role_alter_request_recording_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="response_time",
            field=models.DateTimeField(null=True),
        ),
    ]
