# Generated by Django 4.1.3 on 2023-10-29 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tablet", "0001_initial"),
        ("request", "0006_alter_request_response_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="tablet",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tablet.tablet",
            ),
        ),
    ]
