# Generated by Django 4.1.3 on 2023-10-28 16:17

from django.db import migrations


def create_roles(apps, schema_editor):
    Role = apps.get_model("staff", "Role")
    Role.objects.create(name="Nurse")
    Role.objects.create(name="Helper")


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_roles),
    ]
