# Generated by Django 4.1.3 on 2023-10-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0002_auto_20231028_1817"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="nfc",
            field=models.IntegerField(null=True),
        ),
    ]
