# Generated by Django 4.1.3 on 2023-10-29 16:49

from django.db import migrations


def create_roles(apps, schema_editor):
    Role = apps.get_model("staff", "Role")
    Role.objects.create(name="NURSE")
    Role.objects.create(name="HELPER")
    Role.objects.create(name="DOCTOR")


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0003_alter_staff_nfc"),
    ]

    operations = [
        migrations.RunPython(create_roles),
    ]
