# Generated by Django 4.1.3 on 2023-10-26 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="description",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="name",
        ),
        migrations.AddField(
            model_name="patient",
            name="age",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="doctor_first_visit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="patient",
            name="first_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="hospitalization",
            field=models.IntegerField(
                choices=[(0, "Not Hospitalized"), (1, "Hospitalized"), (2, "Critical")],
                default=0,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="last_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="MedicalExamination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("time", models.DateField(null=True)),
                (
                    "state",
                    models.IntegerField(
                        choices=[(0, "Waiting"), (1, "Processing"), (2, "Finished")],
                        default=0,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_examinations",
                        to="patient.patient",
                    ),
                ),
            ],
        ),
    ]
