# Generated by Django 4.1.3 on 2023-10-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0002_remove_patient_description_remove_patient_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicalexamination",
            name="time",
            field=models.DateTimeField(null=True),
        ),
    ]
