# Generated by Django 4.1.3 on 2023-10-29 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("staff", "0003_alter_staff_nfc"),
        ("patient", "0003_alter_medicalexamination_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tablet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room", models.CharField(max_length=255)),
                (
                    "doctor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="doctor_tablets",
                        to="staff.staff",
                    ),
                ),
                (
                    "nurse",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nurse_tablets",
                        to="staff.staff",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tablets",
                        to="patient.patient",
                    ),
                ),
            ],
        ),
    ]
